[phases.setup]
  nixPkgs = ["...", "php", "php83Packages.composer", "nodejs", "npm"]

[phases.install]
  dependsOn = ["setup"]
  cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
  dependsOn = ["install"]
  cmds = ["npm run build", "php artisan key:generate --force", "php artisan config:clear", "php artisan cache:clear"]

[phases.deploy]
  dependsOn = ["build"]
  cmds = ["php artisan migrate --force"]
